#pragma once

#define NUMBER_OF_DIMENSIONS 3

#define RETURN_BAD_ALLOCATION -1

#define RETURN_INSERT_OK              0
#define RETURN_INSERT_DUPLICATE_POINT 1

#define RETURN_DELETE_OK              0
#define RETURN_DELETE_ERROR_EXISTS    1
#define RETURN_DELETE_POINT_NOT_FOUND 2

#define RETURN_FIND_POINT_FOUND     true
#define RETURN_FIND_POINT_NOT_FOUND false

#define RETURN_EXIT_SUCCESS 0

#define UNREFERENCED_PARAMETER(p) (p)
